IgnorePath '/.snapshots/*'
IgnorePath '/.snapshots'

IgnorePath '/boot/efi/*'
IgnorePath '/boot/vmlinuz-linux'
IgnorePath '/boot/amd-ucode.img'
IgnorePath '/boot/vmlinuz-linux-zen'
IgnorePath '/boot/initramfs-linux.img'
IgnorePath '/boot/initramfs-linux-fallback.img'
IgnorePath '/boot/initramfs-linux-zen.img'
IgnorePath '/boot/initramfs-linux-zen-fallback.img'

IgnorePath '/efi/*'
IgnorePath '/efi'

IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/cups/*'
IgnorePath '/etc/fonts/*'
IgnorePath '/etc/gtk-2.0/*'
IgnorePath '/etc/gtk-3.0/*'
IgnorePath '/etc/libvirt/nwfilter/*'
IgnorePath '/etc/mkinitcpio.d/*'
IgnorePath '/etc/multipath/*'
IgnorePath '/etc/nvme/*'
IgnorePath '/etc/openvpn/*'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/ssl/*'
IgnorePath '/etc/systemd/system/bluetooth.target.wants/*'
IgnorePath '/etc/systemd/system/getty.target.wants/*'
IgnorePath '/etc/systemd/system/multi-user.target.wants/*'
IgnorePath '/etc/systemd/system/network-online.target.wants/*'
IgnorePath '/etc/systemd/system/printer.target.wants/*'
IgnorePath '/etc/systemd/system/sockets.target.wants/*'
IgnorePath '/etc/systemd/system/timers.target.wants/*'
IgnorePath '/etc/xml/*'
IgnorePath '/etc/.updated'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/brlapi.key'
IgnorePath '/etc/environment'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/printcap'
IgnorePath '/etc/pug.bkp'
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/resolv.conf'

IgnorePath '/usr/share/lightdm-webkit/themes/glorious/.git/*'
IgnorePath '/usr/share/applications_backup/*'
IgnorePath '/usr/include/*'
IgnorePath '/usr/lib32/*'
IgnorePath '/usr/lib/*'
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/local/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/doc/*'
IgnorePath '/usr/share/gdb/*'
IgnorePath '/usr/share/glib-2.0/*'
IgnorePath '/usr/share/icons/*'
IgnorePath '/usr/share/info/*'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/qtcreator/*'
IgnorePath '/usr/share/vim/*'

IgnorePath '/var/*'

IgnorePath '/opt/*'

IgnorePath '/etc/group'
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/hostname'
IgnorePath '/etc/iwd'
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/passwd'
IgnorePath '/etc/fstab'

IgnorePath '/usr/lib/modules/*arch1*'
IgnorePath '/usr/lib/modules/*zen1*'

IgnorePath '/etc/os-release'
IgnorePath '/usr/lib/os-release'
