#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh"     # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"      # Loads all defined icons
source "$HOME/.config/sketchybar/userconfig.sh" # Loads all defined icons

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd "$HOME"/.config/sketchybar/helper && make
"$HOME"/.config/sketchybar/helper/helper "$HELPER" >/dev/null 2>&1 &

ITEM_DIR="$HOME/.config/sketchybar/items"            # Directory where the items are configured
export PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
EVENTS_DIR="$HOME/.config/sketchybar/events"         # Directory where the event scripts are stored

# Set up dynamic island helper
DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"
source "$DYNAMIC_ISLAND_DIR/config.sh" # Loads Dynamic-Island config
# run helper program
ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd "$DYNAMIC_ISLAND_DIR"/helper && make
"$DYNAMIC_ISLAND_DIR"/helper/islandhelper "$ISLANDHELPER" &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

bar_config=(
	blur_radius=20
	color="$BASE"
	corner_radius=9
	height=40
	margin=10
	padding_left=10
	padding_right=10
	position=top
	shadow=on
	sticky=on
	y_offset=10
)

icon_defaults=(
	icon.color="$ICON_COLOR"
	icon.font="$NERD_FONT:Bold:16.0"
	icon.padding_left="$PADDINGS"
	icon.padding_right="$PADDINGS"
)

label_defaults=(
	label.color="$TEXT"
	label.font="$FONT:Semibold:13.0"
	label.padding_left="$PADDINGS"
	label.padding_right="$PADDINGS"
)

background_defaults=(
	background.corner_radius=9
	background.height=30
	background.padding_left="$PADDINGS"
	background.padding_right="$PADDINGS"
)

popup_defaults=(
	popup.height=30
	popup.horizontal=false
	popup.background.border_color="$BLUE"
	popup.background.border_width=2
	popup.background.color="$MANTLE"
	popup.background.corner_radius=9
	popup.background.shadow.drawing=on
)
# Setting up the general bar appearance and default values
sketchybar 	--bar 			"${bar_config[@]}"            \
																											\
						--default 	                   						\
												updates=when_shown 						\
												"${icon_defaults[@]}"         \
												"${label_defaults[@]}"        \
												"${background_defaults[@]}"   \
												"${popup_defaults[@]}"

source "$EVENTS_DIR/lock.sh"
source "$EVENTS_DIR/toggle_stats.sh"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/skhd.sh"
source "$ITEM_DIR/separator-left.sh"
source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/spotify.sh"
source "$DYNAMIC_ISLAND_DIR"/item.sh

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/ical.sh"
source "$ITEM_DIR/weather.sh"

source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"

source "$ITEM_DIR/bluetooth.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"

source "$ITEM_DIR/divider.sh"

source "$ITEM_DIR/separator-right.sh"

source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/disk.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
