#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons
source "$HOME/.config/sketchybar/userconfig.sh"  # Loads all defined icons

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd "$HOME"/.config/sketchybar/helper && make
"$HOME"/.config/sketchybar/helper/helper "$HELPER" >/dev/null 2>&1 &

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
export PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
EVENTS_DIR="$HOME/.config/sketchybar/events" # Directory where the event scripts are stored

# Set up dynamic island helper
DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"
source "$DYNAMIC_ISLAND_DIR/config.sh" # Loads Dynamic-Island config
# run helper program
ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd "$DYNAMIC_ISLAND_DIR"/helper && make
"$DYNAMIC_ISLAND_DIR"/helper/islandhelper "$ISLANDHELPER" &



# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance and default values
sketchybar 	--bar 			height=39 																						\
												color="$BASE" 																				\
												shadow=on 																						\
												position=top 																					\
												sticky=on 																						\
												padding_right=10 																			\
												padding_left=10 																			\
												corner_radius=9 																			\
												y_offset=10 																					\
												margin=10 																						\
												blur_radius=20 																				\
																																							\
						--default 	updates=when_shown 																		\
												icon.font="$NERD_FONT:Bold:16.0" 											\
												icon.color="$ICON_COLOR" 															\
												icon.padding_left="$PADDINGS" 												\
												icon.padding_right="$PADDINGS" 												\
												label.font="$FONT:Semibold:13.0" 											\
												label.color="$TEXT" 																	\
												label.padding_left="$PADDINGS" 												\
												label.padding_right="$PADDINGS" 											\
												background.padding_right="$PADDINGS" 									\
												background.padding_left="$PADDINGS" 									\
												background.height=30 																	\
												background.corner_radius=9 														\
												popup.background.border_width=2 											\
												popup.background.corner_radius=9 											\
												popup.background.border_color="$BLUE" 								\
												popup.background.color="$MANTLE" 											\
												popup.background.shadow.drawing=on

source "$EVENTS_DIR/lock.sh"
source "$EVENTS_DIR/toggle_stats.sh"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"
source "$DYNAMIC_ISLAND_DIR"/item.sh

# Right
source "$ITEM_DIR/calendar.sh"

source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"

source "$ITEM_DIR/bluetooth.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"

source "$ITEM_DIR/divider.sh"

source "$ITEM_DIR/stats_separator.sh"

source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/disk.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
