#!/bin/bash
#----------------------------------------------------------------------------
#first section makes the folders for the mount in the /mnt/disks folder so docker containers can have access
#there are 4 entries below as in the video i had 4 remotes amazon,dropbox, google and secure
#you only need as many as what you need to mount for dockers or a network share

mkdir -p /mnt/disks/dropbox
mkdir -p /mnt/disks/googledrive
mkdir -p /mnt/disks/googlephotos
mkdir -p /mnt/disks/onedrive

chown 99:100 /mnt/disks/dropbox
chown 99:100 /mnt/disks/googledrive
chown 99:100 /mnt/disks/googlephotos
chown 99:100 /mnt/disks/onedrive

#This section mounts the various cloud storage into the folders that were created above.

rclone mount --max-read-ahead 1024k --allow-other --dir-cache-time 1000h --cache-dir /mnt/cache/vfs/ --vfs-cache-mode full --vfs-read-ahead 256M  dropbox: /mnt/disks/dropbox --gid 100 --uid 99 &
rclone mount --max-read-ahead 1024k --allow-other --dir-cache-time 1000h --cache-dir /mnt/cache/vfs/ --vfs-cache-mode writes --vfs-read-ahead 256M googledrive: /mnt/disks/googledrive --gid 100 --uid 99 &
rclone mount --max-read-ahead 1024k --dir-cache-time 1000h --allow-other --cache-dir /mnt/cache/vfs/ --vfs-cache-mode full googlephotos: /mnt/disks/googlephotos --gid 100 --uid 99 &
rclone mount --max-read-ahead 1024k --dir-cache-time 1000h --allow-other --cache-dir /mnt/cache/vfs/ --vfs-cache-mode writes --vfs-read-ahead 256M onedrive: /mnt/disks/onedrive --gid 100 --uid 99 &

#echo '"/mnt/disks/dropbox" -fsid=200,async,no_subtree_check *(rw,sec=sys,insecure,anongid=100,anonuid=99,all_squash)' >> /etc/exports
#echo '"/mnt/disks/google" -fsid=201,async,no_subtree_check *(rw,sec=sys,insecure,anongid=100,anonuid=99,all_squash)' >> /etc/exports
#echo '"/mnt/disks/onedrive" -fsid=202,async,no_subtree_check *(rw,sec=sys,insecure,anongid=100,anonuid=99,all_squash)' >> /etc/exports

exportfs -ra