set -U tide_aws_bg_color FF9900
set -U tide_aws_color 232F3E
set -U tide_aws_icon \uf270
set -U tide_character_color 5FD700
set -U tide_character_color_failure FF0000
set -U tide_character_icon \u276f
set -U tide_character_vi_icon_default \u276e
set -U tide_character_vi_icon_replace \u25b6
set -U tide_character_vi_icon_visual V
set -U tide_chruby_bg_color B31209
set -U tide_chruby_color 000000
set -U tide_chruby_icon \ue23e
set -U tide_cmd_duration_bg_color C4A000
set -U tide_cmd_duration_color 000000
set -U tide_cmd_duration_decimals 0
set -U tide_cmd_duration_icon \uf252
set -U tide_cmd_duration_threshold 3000
set -U tide_context_always_display false
set -U tide_context_bg_color 444444
set -U tide_context_color_default D7AF87
set -U tide_context_color_root D7AF00
set -U tide_context_color_ssh D7AF87
set -U tide_context_hostname_parts 1
set -U tide_crystal_bg_color FFFFFF
set -U tide_crystal_color 000000
set -U tide_crystal_icon \u2b22
set -U tide_docker_bg_color 2496ED
set -U tide_docker_color 000000
set -U tide_docker_default_contexts default\x1ecolima
set -U tide_docker_icon \uf308
set -U tide_git_bg_color 4E9A06
set -U tide_git_bg_color_unstable C4A000
set -U tide_git_bg_color_urgent CC0000
set -U tide_git_color_branch 000000
set -U tide_git_color_conflicted 000000
set -U tide_git_color_dirty 000000
set -U tide_git_color_operation 000000
set -U tide_git_color_staged 000000
set -U tide_git_color_stash 000000
set -U tide_git_color_untracked 000000
set -U tide_git_color_upstream 000000
set -U tide_git_icon \uf1d3
set -U tide_git_truncation_length 24
set -U tide_go_bg_color 00ACD7
set -U tide_go_color 000000
set -U tide_go_icon \ue627
set -U tide_java_bg_color ED8B00
set -U tide_java_color 000000
set -U tide_java_icon \ue256
set -U tide_jobs_bg_color 444444
set -U tide_jobs_color 4E9A06
set -U tide_jobs_icon \uf013
set -U tide_kubectl_bg_color 326CE5
set -U tide_kubectl_color 000000
set -U tide_kubectl_icon \u2388
set -U tide_left_prompt_frame_enabled true
set -U tide_left_prompt_items vi_mode\x1eos\x1epwd\x1egit\x1enewline
set -U tide_left_prompt_prefix 
set -U tide_left_prompt_separator_diff_color \ue0b0
set -U tide_left_prompt_separator_same_color \ue0b1
set -U tide_left_prompt_suffix \ue0b0
set -U tide_nix_shell_bg_color 7EBAE4
set -U tide_nix_shell_color 000000
set -U tide_nix_shell_icon \uf313
set -U tide_node_bg_color 44883E
set -U tide_node_color 000000
set -U tide_node_icon \u2b22
set -U tide_os_bg_color 333333
set -U tide_os_color D6D6D6
set -U tide_os_icon \uf179
set -U tide_php_bg_color 617CBE
set -U tide_php_color 000000
set -U tide_php_icon \ue608
set -U tide_private_mode_bg_color F1F3F4
set -U tide_private_mode_color 000000
set -U tide_private_mode_icon \ufaf8
set -U tide_prompt_add_newline_before false
set -U tide_prompt_color_frame_and_connection 6C6C6C
set -U tide_prompt_color_separator_same_color 949494
set -U tide_prompt_icon_connection \u00b7
set -U tide_prompt_min_cols 34
set -U tide_prompt_pad_items true
set -U tide_pwd_bg_color 3465A4
set -U tide_pwd_color_anchors E4E4E4
set -U tide_pwd_color_dirs E4E4E4
set -U tide_pwd_color_truncated_dirs BCBCBC
set -U tide_pwd_icon \uf07c
set -U tide_pwd_icon_home \uf015
set -U tide_pwd_icon_unwritable \uf023
set -U tide_pwd_markers \x2ebzr\x1e\x2ecitc\x1e\x2egit\x1e\x2ehg\x1e\x2enode\x2dversion\x1e\x2epython\x2dversion\x1e\x2eruby\x2dversion\x1e\x2eshorten_folder_marker\x1e\x2esvn\x1e\x2eterraform\x1eCargo\x2etoml\x1ecomposer\x2ejson\x1eCVS\x1ego\x2emod\x1epackage\x2ejson
set -U tide_right_prompt_frame_enabled false
set -U tide_right_prompt_items status\x1ecmd_duration\x1econtext\x1ejobs\x1enode\x1evirtual_env\x1erustc\x1ejava\x1ephp\x1echruby\x1ego\x1ekubectl\x1etoolbox\x1eterraform\x1eaws\x1enix_shell\x1ecrystal\x1etime
set -U tide_right_prompt_prefix \ue0b2
set -U tide_right_prompt_separator_diff_color \ue0b2
set -U tide_right_prompt_separator_same_color \ue0b3
set -U tide_right_prompt_suffix 
set -U tide_rustc_bg_color F74C00
set -U tide_rustc_color 000000
set -U tide_rustc_icon \ue7a8
set -U tide_shlvl_bg_color 808000
set -U tide_shlvl_color 000000
set -U tide_shlvl_icon \uf120
set -U tide_shlvl_threshold 1
set -U tide_status_bg_color 2E3436
set -U tide_status_bg_color_failure CC0000
set -U tide_status_color 4E9A06
set -U tide_status_color_failure FFFF00
set -U tide_status_icon \u2714
set -U tide_status_icon_failure \u2718
set -U tide_terraform_bg_color 800080
set -U tide_terraform_color 000000
set -U tide_terraform_icon \x1d
set -U tide_time_bg_color D3D7CF
set -U tide_time_color 000000
set -U tide_time_format \x25r
set -U tide_toolbox_bg_color 613583
set -U tide_toolbox_color 000000
set -U tide_toolbox_icon \u2b22
set -U tide_vi_mode_bg_color_default 949494
set -U tide_vi_mode_bg_color_insert 87AFAF
set -U tide_vi_mode_bg_color_replace 87AF87
set -U tide_vi_mode_bg_color_visual FF8700
set -U tide_vi_mode_color_default 000000
set -U tide_vi_mode_color_insert 000000
set -U tide_vi_mode_color_replace 000000
set -U tide_vi_mode_color_visual 000000
set -U tide_vi_mode_icon_default D
set -U tide_vi_mode_icon_insert I
set -U tide_vi_mode_icon_replace R
set -U tide_vi_mode_icon_visual V
set -U tide_virtual_env_bg_color 444444
set -U tide_virtual_env_color 00AFAF
set -U tide_virtual_env_icon \ue73c
