name: Dead code analysis

on: [push]

jobs:

  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
